### ISSUE TITLE
Cleanup of `ManagedOSVersion` orphans

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/rancheros-operator#17]
At the moment ManagedOSVersion created by the controller don't have an owner set, so cleaning up a ManagedOSVersionChannel doesn't cleanup available versions.

Ideally we should set the VersionChannel as owner of ManagedOSVersion, allowing the resources to be cleaned up in cascade.

e.g. when creating the resource
```golang
OwnerReferences: []metav1.OwnerReference{
		*metav1.NewControllerRef(..., schema.GroupVersionKind{
			Group:   v1alpha1.SchemeGroupVersion.Group,
			Version: v1alpha1.SchemeGroupVersion.Version,
			Kind:    "...",
		}),
	},
```

Follow up of : #14

**Comment by davidcassany** [comment]
I am starting to have a look at this one
