### ISSUE TITLE
Check using kind for testing the ros-operator

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/rancheros-operator#2]
@mudler mentioned that kind can be used to test the operator in a more speedy and simpler way. Investigate that and introduce kind if possible to speed up our CI

**Comment by mudler** [comment]
for reference: https://github.com/kubernetes-sigs/kind. But maybe also `k3d` could do the job as well https://k3d.io/v5.3.0/.

Note also that there are github actions as well: https://github.com/helm/kind-action
