### ISSUE TITLE
Node is not given a hostname on first boot after install

### ISSUE THREAD

**Issue by agracey** [rancher-sandbox/rancheros-operator#31]
You need an extra reboot for the hostname to get set. This causes issues with the k3s node name getting changed.

I'm not sure this is the right place to file this ticket.

**Comment by kkaempf** [comment]
Where and when are you trying to set the hostname ?

**Comment by kkaempf** [comment]
We now usually put
```
spec:
  cloudConfig:
    hostname: ros-node-{{ trunc 4 .MachineID }}
```
into the machine registration to have the hostname set during initial deployment.

Maybe this should be made standard in all examples ? (It certainly needs more documentation :wink:)

**Comment by agracey** [comment]
I hadn't set anything so was just taking the default `rancher-xxxxx` that got added. I'll add the specific line to see if it changes the behavior in my set up.

**Comment by agracey** [comment]
Confirmed this is not an issue when the hostname is set in the cloudConfig settings

**Comment by mudler** [comment]
FYI it is documented here: https://rancher-sandbox.github.io/cOS-toolkit/docs/reference/cloud_init/#stagesstage_idstep_namehostname
